const LIST_RECORDS = 'LIST_RECORDS';
const UPDATE_RECORD = 'UPDATE_RECORD';
const CREATE_RECORD = 'CREATE_RECORD';
const DELETE_RECORD = 'DELETE_RECORD';

export {LIST_RECORDS, UPDATE_RECORD, CREATE_RECORD, DELETE_RECORD};
