default: &default
  adapter: mysql2
  host: localhost
  username: root

development:
  <<: *default
  database: bp

test:
  <<: *default
  database: bp_test

production:
  <<: *default
  database: bp_production
