# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ffe89b9493be6e179c6eda4b2538cfb79bdee8ad6935dfa9377872b09edb968bd8a28e2dff795b7aea86af31e58eb20194e8876b9916031a5d7e0d35a18f68a

test:
  secret_key_base: 4798d459e2591c332338ca7c237a3ed743db9a698f6e639abd7fe3dffad556828563309a5a172ed86666c53660c4bf551d32fb8611cfc260826342384d9380f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
