source 'https://rubygems.org'

gem 'jbuilder', '~> 2.5'
gem 'mysql2'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'swagger-blocks'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'guard-rspec', require: false
  gem 'listen', '~> 3.0.5'
  gem 'pry-rails'
  gem 'rubocop'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'spring'
end

group :test do
  gem 'airborne'
  gem 'factory_girl_rails'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-rails'
  gem 'rspec-support'
  gem 'rspec'
  gem 'faker'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
